### ISSUE TITLE
Decouple noflow from nokit dependencies

### ISSUE THREAD

**Issue by magnus-** [ysmood/noflow#1]
1. For transpiling from coffeescript, use tools or write js from bottom to top on the basis of existed code behavior?
2. More details about assignments and schedulings

@ysmood

**Comment by ysmood** [comment]
Just 100 lines of code, I think it won't be a bad idea to rewrite it from the bottom. 

I have to focus on Yaku, one of the must dependency of noflow. So, do you have time for refactor?

**Comment by magnus-** [comment]
sure thing.
but what' bout test cases, should I use **ken** or **mocha**?

**Comment by ysmood** [comment]
Please use ken. mocha is really a mess to my one year experience of it. That's why I wrote ken ( 験：けん). For example, mocha doesn't support concurrent tests, you have to wait for one async task after another. Noflow highly dependents on asynchronous, when you use mocha the test may take much more  time to finish.

**Comment by ysmood** [comment]
noflow will have only two `dependencies`: yaku, jhash.
- yaku: for Promise
- jhash: for etag

only one `devDependencies`: nokit.
- nokit: unit test, automation, etc

**Comment by magnus-** [comment]
My previous experience also suggests me to use ken instead of mocha. I once wrote more extra code to fulfill the promise for async calling chains.

great, i'll create a branch to do the work...

**Comment by magnus-** [comment]
forgot to ask that by naming the branching which solution should I choose version based or behavior based?

**Comment by ysmood** [comment]
behavior please, for example, `refactor/decouple-nokit`, `refactor/translate-to-js`

**Comment by ysmood** [comment]
tags for versioning

**Comment by ysmood** [comment]
I've refactored the API, now it's much cleaner. 938174c47b5544ffe020d45b35480e6b66d4e8f0

Read the changelog of nokit for more details: https://github.com/ysmood/nokit/blob/master/doc/changelog.md

**Comment by ysmood** [comment]
Now noflow doesn't have to depend on `jhash` any more.
