### ISSUE TITLE
Import unit tests from nokit

### ISSUE THREAD

**Issue by ysmood** [ysmood/noflow#5]
I wrote an example: https://github.com/ysmood/noflow/blob/04718c6e4df7039fc101d8b5ecdb2e4119b7d508/test/basic-api.js

If you don't feel comfortable about it, please let me know.

**Comment by magnus-** [comment]
great
I'll do my best to import the test code

**Comment by ysmood** [comment]
I have changed the api of `ken`. If you have any problem with the unit test, please update the dependencies first.

**Comment by magnus-** [comment]
You mean I should modify ken first when I've got some problems in this scenario?

**Comment by ysmood** [comment]
No, just npm install is enough.

2015年9月7日(月) 19:07 Magnus notifications@github.com:

**Comment by ysmood** [comment]
No, just npm install is enough.

**Comment by magnus-** [comment]
233333
I got your points!
